import Head from "next/head";
import Image from "next/image";
import { About, Gallery, Hero } from "../components";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Services from "../components/Services";
import Team from "../components/Team";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Services />
      <div>
        <About />
      </div>
      <Team />
      <Gallery />
      <Contact />
    </div>
  );
}
