import { groq } from "next-sanity";
import Head from "next/head";
import Image from "next/image";
import { About, Gallery, Hero } from "../components";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Services from "../components/Services";
import Team from "../components/Team";
import client from "../sanity";
import styles from "../styles/Home.module.css";

export default function Home({ about, team, gallery, services }) {
  console.log(services);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Services services={services} />
      <div>
        <About about={about} />
      </div>
      <Team team={team} />
      <Gallery gallery={gallery} />
      <Contact />
    </div>
  );
}

export async function getStaticProps() {
  const team = await client.fetch(groq`*[_type == "team"]{
    ...,
  
    
  }`);

  const about = await client.fetch(groq`*[_type == "about"]{...,}`);
  const gallery = await client.fetch(groq`*[_type == "gallery"]{...,}`);
  const services = await client.fetch(groq`*[_type == "services"]{...,}`);

  return {
    props: { team, about, gallery, services }, // will be passed to the page component as props
  };
}
